
package carplatescrambler;

import carplatescrambler.Models.PlateSequence;
import carplatescrambler.PlateBuilder.PlateBuilder;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;

class GUI extends javax.swing.JFrame {
    static String searchword = "FEHLER";
    /**
     * Creates new form GUI
     */
    private GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel label_Title = new javax.swing.JLabel();
        javax.swing.JLabel label_searchword = new javax.swing.JLabel();
        tf_searchword = new javax.swing.JTextField();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        ta_output = new javax.swing.JTextArea();
        javax.swing.JButton b_search = new javax.swing.JButton();
        javax.swing.JButton b_generate = new javax.swing.JButton();
        javax.swing.JButton jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        label_Title.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 24)); // NOI18N
        label_Title.setText("Auto-Kennzeichen-Scrabble");

        label_searchword.setText("Suchwort:");

        tf_searchword.setText("INFORMATIK");
        tf_searchword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_searchwordActionPerformed(evt);
            }
        });

        ta_output.setColumns(20);
        ta_output.setRows(5);
        jScrollPane1.setViewportView(ta_output);

        b_search.setText("Suchen");
        b_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_searchActionPerformed(evt);
            }
        });

        b_generate.setText("Generate");
        b_generate.setEnabled(true);
        b_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_generateActionPerformed(evt);
            }
        });

        jButton1.setText("Hilfe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_searchword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_searchword))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(b_generate)
                                .addGap(18, 18, 18)
                                .addComponent(b_search)))
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(label_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Title)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_searchword)
                    .addComponent(tf_searchword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_generate)
                    .addComponent(b_search)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {
    }

    private void tf_searchwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_searchwordActionPerformed
        // TODO add your handling code here:
        ScrabbleSearchWord();
    }//GEN-LAST:event_tf_searchwordActionPerformed

    private void b_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_searchActionPerformed
        ScrabbleSearchWord();
       
    }//GEN-LAST:event_b_searchActionPerformed

    private void ScrabbleSearchWord() {
       ;
        searchword = tf_searchword.getText().toUpperCase();
        tf_searchword.setText(searchword);
        Pattern p = Pattern.compile("[^öÖäÄüÜa-zA-Z]*$");
        Matcher m = p.matcher(searchword);
        if(m.find() && !searchword.contains(" "))
        {
            String output = "";
            
            output+="Wortlänge: " + searchword.length() + "\n";
            if(searchword.contains("Ä"))
            {
                ta_output.setText(output+"Anzahl Kombinationsmöglichkeiten: 0");
                ta_output.setSelectionStart(0);
                ta_output.setSelectionEnd(0); 
            } else {
                PlateBuilder plateBuilder = new PlateBuilder(searchword);
                List<PlateSequence> scrabble = plateBuilder.scrabble();
                output+="Anzahl Kombinationsmöglichkeiten: "+scrabble.size();

                StringBuilder outputBuilder = new StringBuilder(output);
                for (PlateSequence plateSequence : scrabble) {
                    outputBuilder.append("\n").append(plateSequence.getPlateSequence()).append("\n");
                }
                output = outputBuilder.toString();

                ta_output.setText(output);
                ta_output.setSelectionStart(0);
                ta_output.setSelectionEnd(0);
            }
            
        } else {
            ta_output.setText("FEHLER: Bitte keine Sonderzeichen, Leerzeichen oder Zahlen eingeben!");
        }
    }

    private void b_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_generateActionPerformed
        //DrawPlates.paint(tf_searchword.getText().toUpperCase());
        searchword = tf_searchword.getText().toUpperCase();
        tf_searchword.setText(searchword);
        JFrame f = new JFrame();
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.setSize(700, 200);
        f.add(new DrawPanel());
        f.setVisible(true);
    }//GEN-LAST:event_b_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    private javax.swing.JTextArea ta_output;
    private javax.swing.JTextField tf_searchword;
    // End of variables declaration                   
}
